apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: smgywt8yo-java-springboot
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: rhtap-quay-quay-rhtap-quay.apps.rosa.kx-0bfa15770e.lftb.p3.openshiftapps.com/rhtap/rhtap-qe-java-springboot:c0230be78b1f9bb45676b31e405c1b573c35effa@sha256:0ea7c7e4a2eead470707e1e29f83f82855018a05f1070e214e902c549ac04175
          name: container-image
